update contact page to show new contact information
meaghanlewis/TestWebAppProject pull request #10
Opened 2017-09-09 00:25 UTC by meaghanlewis

## Title
Update contact page

## Summary of changes
I updated the contact page

## Notes
Show some new information

2017-09-14 16:56 UTC, meaghanlewis commented on TestWebAppProject/Views/Home/Contact.cshtml
> +    ViewData["Title"] = "Contactttttt";
comment on line 2

2017-09-14 16:57 UTC, meaghanlewis commented on TestWebAppProject/Views/Home/Contact.cshtml
>  ﻿@{
line 1

2017-09-14 16:57 UTC, meaghanlewis commented on TestWebAppProject/Views/Home/Contact.cshtml
>  <h3>@ViewData["Message"]</h3>
hello?

2017-09-14 18:02 UTC, meaghanlewis commented on TestWebAppProject/Views/Home/Contact.cshtml
>  <h2>@ViewData["Title"].</h2>
title

2017-09-14 18:02 UTC, meaghanlewis commented on TestWebAppProject/Views/Home/Contact.cshtml
>  <h2>@ViewData["Title"].</h2>
replying

2017-09-27 22:04 UTC, meaghanlewis commented on TestWebAppProject/Views/Home/Contact.cshtml
> +    ViewData["Title"] = "Contactttttt";
something

2017-10-11 11:31 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>              ViewData["Message"] = "Your application description page.";
commenting

2017-11-16 23:39 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
> +            ViewData["Message"] = "Your application description page.3030030034";
comment here

2017-11-16 23:40 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
> +            ViewData["Message"] = "Your application description page.3030030034";
replying

2017-11-20 23:16 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>          public IActionResult About()
comment on 16

2017-11-20 23:17 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>          {
comment on line 17

2017-11-30 18:49 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>              return View();
comment on 21

2018-01-30 22:09 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
yasss

2018-02-20 18:39 UTC, meaghanlewis-tester approved these changes

2018-03-27 16:55 UTC, ghfvs-tester requested changes

2018-03-27 16:55 UTC, ghfvs-tester commented on .gitignore
> +*.pyc
.pyc?

2018-03-27 16:55 UTC, ghfvs-tester commented on TestWebAppProject/Controllers/HomeController.cs
>          public IActionResult About()
ok

2018-11-01 21:05 UTC, merged