update rename locals to false
meaghanlewis/TestWebAppProject pull request #13
Opened 2017-11-10 00:19 UTC by meaghanlewis

## Title

## Summary of changes

## Notes

2017-11-20 23:25 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
>      "sourceMap": false
comment on line 22

2017-11-20 23:26 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
comment on line 19

2017-11-21 18:52 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
>      },
}

2017-11-21 18:52 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
>      },
replying

2017-11-28 19:35 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
>      // Optionally generate .map file
comment here

2018-02-20 18:40 UTC, meaghanlewis-tester approved these changes
LGTM!

2018-02-20 18:42 UTC, meaghanlewis-tester requested changes
can you change the thing?

2018-03-08 19:45 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
>        "enabled": true,
something

2018-03-08 22:09 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
},
    // Optionally generate .map file
    "sourceMap": false
  }

2018-03-08 22:10 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
https://github.com/meaghanlewis/TestWebAppProject/issues/5

2018-03-08 22:12 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
https://media2.giphy.com/media/OODXXtfUiUmSdi3ExL/giphy.gif

2018-03-08 22:12 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
![img](https://media2.giphy.com/media/OODXXtfUiUmSdi3ExL/giphy.gif)

2018-03-08 22:12 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
:)

2018-03-08 22:13 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
👍

2018-03-08 22:13 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
:thumbs_up:

2018-03-08 22:13 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
:thumbsup:

2018-03-08 22:14 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
>      "sourceMap": false
https://github.com/meaghanlewis/TestWebAppProject/issues/5

2018-03-08 22:15 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
>      "sourceMap": false
{
    "outputFileName": "wwwroot/js/site.min.js",
    "inputFiles": [
      "wwwroot/js/site.js"
    ],
    // Optionally specify minification options
    "minify": {
      "enabled": true,
      "renameLocals": true
    },
    // Optionally generate .map file
    "sourceMap": false
  }

2018-03-08 22:16 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
>        "enabled": true,
start review

2018-03-08 22:16 UTC, meaghanlewis commented on TestWebAppProject/bundleconfig.json
> +      "renameLocals": false
finish

2018-03-26 18:40 UTC, ghfvs-tester approved these changes
LGTM

2018-03-26 18:40 UTC, ghfvs-tester commented on TestWebAppProject/bundleconfig.json
>      // Optionally specify minification options
minify?

2018-03-26 18:40 UTC, ghfvs-tester commented on TestWebAppProject/bundleconfig.json
>      // Optionally specify minification options
yep!

2018-03-26 18:41 UTC, ghfvs-tester reviewed
something something

2018-03-26 18:43 UTC, ghfvs-tester requested changes

2018-03-26 18:43 UTC, ghfvs-tester commented on TestWebAppProject/bundleconfig.json
>      // Optionally generate .map file
not sure about this

2018-03-26 18:43 UTC, ghfvs-tester commented on TestWebAppProject/bundleconfig.json
>      // Optionally generate .map file
not sure about this

2018-03-26 18:43 UTC, ghfvs-tester commented on TestWebAppProject/bundleconfig.json
>      "minify": {
yes

2018-03-26 18:44 UTC, ghfvs-tester approved these changes

2018-12-18 18:25 UTC, merged