Branchbranch
meaghanlewis/TestWebAppProject pull request #17
Opened 2018-03-08 21:47 UTC by meaghanlewis

## Title

## Summary of changes

## Notes

2018-03-22 12:02 UTC, meaghanlewis commented on TestWebAppProject/Program.cs
> +	public class Program
fix the indentation

2018-03-22 12:20 UTC, meaghanlewis reviewed
just leaving a comment

2018-04-05 03:29 UTC, ghfvs-tester requested changes
comments and request

2018-04-05 03:29 UTC, ghfvs-tester commented on TestWebAppProject/Startup.cs
> +		// This method gets called by tffhe runtime. Use this method to add services to the container.
new review

2018-04-05 03:29 UTC, ghfvs-tester commented on TestWebAppProject/Startup.cs
> +		public void ConfigureServices(IServiceCollection services)
2nd comment! <p> paragraph </p>

2018-04-12 23:27 UTC, ghfvs-tester requested changes

2018-04-12 23:27 UTC, ghfvs-tester commented on TestWebAppProject/Program.cs
>  namespace TestWebAppProject
???

2018-04-12 23:27 UTC, ghfvs-tester commented on TestWebAppProject/Program.cs
> +﻿using Microsoft.AspNetCore.Hosting;
???? lalala

2018-04-12 23:32 UTC, ghfvs-tester commented on TestWebAppProject/Class.cs
> +namespace TestWebAppProject
cool!!!

2018-04-12 23:34 UTC, ghfvs-tester approved these changes

2018-04-12 23:34 UTC, ghfvs-tester commented on TestWebAppProject/Class.cs
> +    public class Class
public?

2018-04-12 23:34 UTC, ghfvs-tester commented on TestWebAppProject/Class.cs
> +    public class Class
another review

2020-10-01 01:41 UTC, closed without merging