Unit test solution
meaghanlewis/TestWebAppProject pull request #22
Opened 2018-03-27 21:31 UTC by meaghanlewis

## Title

## Summary of changes

## Notes

2018-03-27 21:33 UTC, ghfvs-tester approved these changes

2018-03-27 21:33 UTC, ghfvs-tester commented on UnitTestProject2/UnitTestProject2/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTitle("UnitTestProject2")]
nice

2018-03-27 21:33 UTC, ghfvs-tester commented on UnitTestProject2/UnitTestProject2/Properties/AssemblyInfo.cs
> +//      Revision
nice

2018-03-27 21:33 UTC, ghfvs-tester approved these changes

2018-03-27 21:33 UTC, ghfvs-tester approved these changes

2018-03-27 21:33 UTC, ghfvs-tester commented on UnitTestProject2/UnitTestProject2/Properties/AssemblyInfo.cs
> +// Setting ComVisible to false makes the types in this assembly not visible
cool

2018-04-05 03:02 UTC, meaghanlewis reviewed
"My review"

2018-04-05 03:02 UTC, meaghanlewis commented on UnitTestProject2/UnitTestProject2/UnitTest1.cs
> +    [TestClass]
LGTM

2018-04-05 03:28 UTC, ghfvs-tester requested changes
looking good, but a few comments to address

2020-10-01 01:41 UTC, closed without merging