windows form application solution
meaghanlewis/TestWebAppProject pull request #23
Opened 2018-04-10 22:09 UTC by meaghanlewis

## Title

## Summary of changes

## Notes

2018-04-13 00:05 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +// General Information about an assembly is controlled through the following
!!!!!

2018-04-13 00:05 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTitle("WindowsFormsApplication1")]
!!!!

2018-04-13 00:05 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCompany("")]
"""""

2018-04-13 00:09 UTC, ghfvs-tester approved these changes

2018-04-13 00:09 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.Designer.cs
> +namespace WindowsFormsApplication1.Properties
name

2018-04-13 00:10 UTC, ghfvs-tester requested changes

2018-04-13 00:10 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.resx
> +  <!--
la

2018-04-13 00:10 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.resx
> +
di

2018-04-13 00:10 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.resx
> +
da

2018-04-13 00:13 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Program.cs
> +    static class Program
1

2018-04-13 00:13 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Program.cs
> +namespace WindowsFormsApplication1
2

2018-04-13 00:13 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Program.cs
> +        static void Main()
another

2018-04-13 00:14 UTC, ghfvs-tester approved these changes

2018-04-13 00:14 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Program.cs
> +            Application.SetCompatibleTextRenderingDefault(false);
review comment

2018-07-20 21:48 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.resx
> +
ttttttt

2018-07-20 21:48 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.resx
> +
llllllloook

2018-12-18 18:25 UTC, merged