add new solution
meaghanlewis/TestWebAppProject pull request #24
Opened 2018-04-13 03:34 UTC by ghfvs-tester

## Title

## Summary of changes

## Notes

2018-04-13 03:36 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +// associated with an assembly.
cool

2018-04-13 03:36 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +[assembly: AssemblyDescription("")]
lgtm

2018-04-16 23:06 UTC, ghfvs-tester reviewed
can i comment?

2018-04-17 21:49 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.resx
> +    Version 2.0
test comment

2018-04-17 21:49 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.resx
> +    Version 2.0
reply

2018-04-17 21:49 UTC, meaghanlewis approved these changes
lalala

2018-04-17 23:46 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTitle("WindowsFormsApplication1")]
<3

2018-04-17 23:46 UTC, meaghanlewis approved these changes

2018-04-18 01:32 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Settings.settings
> +    <Profile Name="(Default)" />
comment!!!1 >?<<>>>

2018-04-18 01:33 UTC, meaghanlewis approved these changes

2018-04-18 01:33 UTC, meaghanlewis approved these changes
lgtm!!!!!!!

2018-04-18 01:47 UTC, meaghanlewis requested changes
nope

2018-04-18 01:47 UTC, meaghanlewis approved these changes

2018-04-18 01:47 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/App.config
> +        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
1

2018-04-18 01:47 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/App.config
> +<configuration>
2

2018-04-18 01:47 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/App.config
> +    </startup>
3

2018-04-18 01:47 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1.sln
> +Global
4

2018-04-18 20:46 UTC, meaghanlewis approved these changes
LGTM :thumbs_up:

2018-04-18 20:46 UTC, meaghanlewis requested changes
nope

2018-05-01 22:30 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Form1.cs
> +		public Form1()
comment from editor

2018-05-01 23:10 UTC, meaghanlewis approved these changes

2018-05-01 23:10 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.Designer.cs
> +namespace WindowsFormsApplication1.Properties
start a review

2018-05-01 23:10 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/Resources.Designer.cs
> +
kakaijfoa

2018-05-02 17:07 UTC, meaghanlewis submitted a review, later dismissed

2018-05-02 17:07 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +// associated with an assembly.
reply

2018-06-08 17:18 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2018")]
add a new comment

2018-06-08 17:19 UTC, meaghanlewis commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCulture("")]
another one?

2018-06-12 18:12 UTC, ghfvs-tester reviewed
new comment

2018-06-12 18:12 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +
new comment

2018-06-12 18:15 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +//      Revision
comment

2018-06-12 18:16 UTC, ghfvs-tester reviewed
new comment

2018-06-12 18:16 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +// to COM components.  If you need to access a type in this assembly from
new comment

2018-06-12 18:16 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +// to COM components.  If you need to access a type in this assembly from
new reply

2018-06-12 18:17 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +//      Minor Version
comment

2018-06-12 18:17 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +//      Minor Version
reply

2018-06-12 18:19 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +// You can specify all the values or you can default the Build and Revision Numbers
coment

2018-06-12 18:19 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +// You can specify all the values or you can default the Build and Revision Numbers
reply

2018-06-12 18:20 UTC, ghfvs-tester commented on WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs
> +// You can specify all the values or you can default the Build and Revision Numbers
reply and start revie

2018-07-17 21:04 UTC, meaghanlewis approved these changes

2018-07-17 21:04 UTC, merged

2018-07-17 21:04 UTC, meaghanlewis reviewed
comment