Update HomeController.cs
meaghanlewis/TestWebAppProject pull request #3
Opened 2017-08-17 18:30 UTC by meaghanlewis

Add another message in the home controller.

**v important**

# BIG BIG BIG

> test PR

[https://github.com/mastahyeti/OctoGAS](url)

- 1
- 2
- 3

1. one
2. two
3. three

2017-08-18 19:37 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
> +            ViewData["Message"] = "Your application body.";
1

2017-08-18 19:41 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
> +            ViewData["Message"] = "Your application body.";
replying

2017-08-18 19:48 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
> +            ViewData["Message"] = "Your application body.";
<html>
<head>
<title>Title of the document</title>
</head>

<body>
The content of the document......
</body>

</html>

2017-08-18 20:51 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>              return View();
https://github.com/github/VisualStudio/issues/1159

2017-08-22 20:48 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>          public IActionResult About()
comment

2017-08-22 22:53 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>          {
1

2017-08-22 22:54 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>              ViewData["Message"] = "Your application description page.";
2

2017-08-22 22:54 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
1

2017-08-22 22:54 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
1

2017-08-22 22:54 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
comment

2017-08-22 22:56 UTC, meaghanlewis commented on TestWebAppProject/appsettings.Development.json
>    "Logging": {
comment here

2017-08-22 22:57 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
comment here

2017-08-22 22:58 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
comment on line 7

2017-08-22 23:00 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
>    <ItemGroup>
comment on line 8

2017-08-22 23:02 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
comment on line 20

2017-08-22 23:02 UTC, meaghanlewis commented on TestWebAppProject/appsettings.Development.json
>      }
blaha

2017-08-22 23:02 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
> +    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
line 10

2017-08-22 23:03 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
>    </ItemGroup>
line 15

2017-08-22 23:04 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
comment on line 7

2017-08-22 23:04 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
> +    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
comment on line 10

2017-08-22 23:04 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>          }
comment on line 22

2018-03-27 16:35 UTC, ghfvs-tester approved these changes

2018-03-27 16:35 UTC, ghfvs-tester commented on TestWebAppProject/TestWebAppProject.csproj
>      <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
start a review

2018-03-27 16:35 UTC, ghfvs-tester commented on TestWebAppProject/Views/Shared/Error.cshtml
> +
looks good!

2018-03-27 16:35 UTC, ghfvs-tester commented on TestWebAppProject/appsettings.Development.json
> +      "Default": "Error",
error?

2018-04-05 14:47 UTC, ghfvs-tester requested changes
https://ci.appveyor.com/project/github-windows/visualstudio/build/2.4.99.2033/artifacts

2018-04-05 15:07 UTC, ghfvs-tester approved these changes

2018-04-05 15:07 UTC, ghfvs-tester commented on TestWebAppProject/Views/Shared/Error.cshtml
> +<h3>Development Mode</h3>
error1

2018-04-05 15:07 UTC, ghfvs-tester commented on TestWebAppProject/Views/Shared/Error.cshtml
> +<p>
error2

2018-04-12 22:17 UTC, ghfvs-tester approved these changes

2018-04-12 22:18 UTC, ghfvs-tester reviewed
lgtm

2018-04-12 22:21 UTC, ghfvs-tester requested changes

2018-04-12 22:21 UTC, ghfvs-tester commented on TestWebAppProject/appsettings.Development.json
>        "Microsoft": "Information"
how about "microsoft" -> ~cross~

2018-04-12 22:22 UTC, ghfvs-tester commented on TestWebAppProject/Views/Shared/Error.cshtml
> +    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
<strong>dev</strong>

2018-04-12 23:16 UTC, meaghanlewis reviewed
can i comment here

2018-05-29 20:44 UTC, meaghanlewis commented on TestWebAppProject/Views/Shared/Error.cshtml
> +
reply

2018-06-12 20:18 UTC, ghfvs-tester approved these changes

2018-06-12 20:18 UTC, ghfvs-tester commented on TestWebAppProject/Controllers/HomeController.cs
>              return View();
start a new review

2018-06-12 20:18 UTC, ghfvs-tester commented on TestWebAppProject/Controllers/HomeController.cs
>          }
comment 2

2018-06-12 20:18 UTC, ghfvs-tester commented on TestWebAppProject/Controllers/HomeController.cs
add another

2018-06-12 20:18 UTC, ghfvs-tester commented on TestWebAppProject/Controllers/HomeController.cs
reply

2018-06-12 20:21 UTC, ghfvs-tester approved these changes

2018-06-12 20:21 UTC, ghfvs-tester commented on TestWebAppProject/TestWebAppProject.csproj
>    <ItemGroup>
new review

2018-06-12 20:21 UTC, ghfvs-tester commented on TestWebAppProject/TestWebAppProject.csproj
>    <ItemGroup>
reply

2018-06-12 20:21 UTC, ghfvs-tester commented on TestWebAppProject/TestWebAppProject.csproj
>    <ItemGroup>
reply2

2018-06-12 20:21 UTC, ghfvs-tester commented on TestWebAppProject/TestWebAppProject.csproj
>      <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
How about this?

2018-06-14 17:50 UTC, meaghanlewis commented on TestWebAppProject/TestWebAppProject.csproj
>      <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
start a new review

2018-06-14 17:50 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>              return View();
add new comment

2018-06-14 17:50 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
> +            return View();
new pending comment!!!!

2018-06-14 17:50 UTC, meaghanlewis reviewed
lgtm

2018-06-14 17:50 UTC, meaghanlewis commented on TestWebAppProject/appsettings.Development.json
>        "System": "Information",
new review

2018-06-14 17:50 UTC, meaghanlewis commented on TestWebAppProject/appsettings.Development.json
>        "System": "Information",
single comment

2018-06-14 21:15 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>              return View();
reply

2018-06-14 22:14 UTC, meaghanlewis commented on TestWebAppProject/Controllers/HomeController.cs
>              return View();
reply

2018-07-19 14:30 UTC, merged