add
meaghanlewis/TestWebAppProject pull request #33
Opened 2018-07-27 04:54 UTC by meaghanlewis

## Title

## Summary of changes

## Notes

2018-08-07 23:12 UTC, ghfvs-tester approved these changes
lgmt

2018-08-07 23:13 UTC, ghfvs-tester commented on UnitTestProject1/UnitTestProject1/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTrademark("")]
review

2018-08-07 23:13 UTC, ghfvs-tester requested changes

2018-08-07 23:13 UTC, ghfvs-tester commented on UnitTestProject1/UnitTestProject1/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTrademark("")]
ldksksk

2018-08-09 20:31 UTC, meaghanlewis commented on UnitTestProject1/UnitTestProject1/UnitTest1.cs
> +        [TestMethod]
cool test

2018-08-09 20:31 UTC, meaghanlewis commented on UnitTestProject1/UnitTestProject1/UnitTest1.cs
> +        [TestMethod]
some reply

2018-08-16 20:27 UTC, meaghanlewis reviewed
aaaa

2018-08-16 20:27 UTC, meaghanlewis reviewed
lalalalala

2018-08-16 20:27 UTC, meaghanlewis commented on UnitTestProject1/UnitTestProject1/UnitTest1.cs
> +    [TestClass]
lalalalala

2018-09-13 18:21 UTC, merged